name: 'k6-reporter'
description: 'GitHub Actions k6 Report Generation for k6'
author: 'hipcamp'
inputs:
  filename:
    required: true
    description: 'report file from k6 run'
  response-filename:
    required: true
    description: 'response objects output file'
  base-url:
    required: true
    description: 'the url supplied to k6 for testing'
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
